<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LemmaSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $lemmas = [
            // Kata kerja (Verba) - label_id = 1 (cakapan), 4 (kiasan), atau NULL
            ['label_id' => null, 'name' => 'makan', 'name_tagged' => 'makan'],
            ['label_id' => null, 'name' => 'minum', 'name_tagged' => 'minum'],
            ['label_id' => null, 'name' => 'tidur', 'name_tagged' => 'tidur'],
            ['label_id' => null, 'name' => 'bangun', 'name_tagged' => 'bangun'],
            ['label_id' => null, 'name' => 'berjalan', 'name_tagged' => 'berjalan'],
            ['label_id' => null, 'name' => 'berlari', 'name_tagged' => 'berlari'],
            ['label_id' => null, 'name' => 'melompat', 'name_tagged' => 'melompat'],
            ['label_id' => null, 'name' => 'menulis', 'name_tagged' => 'menulis'],
            ['label_id' => null, 'name' => 'membaca', 'name_tagged' => 'membaca'],
            ['label_id' => null, 'name' => 'belajar', 'name_tagged' => 'belajar'],
            ['label_id' => null, 'name' => 'mengajar', 'name_tagged' => 'mengajar'],
            ['label_id' => null, 'name' => 'bekerja', 'name_tagged' => 'bekerja'],
            ['label_id' => null, 'name' => 'bermain', 'name_tagged' => 'bermain'],
            ['label_id' => null, 'name' => 'bernyanyi', 'name_tagged' => 'bernyanyi'],
            ['label_id' => null, 'name' => 'menari', 'name_tagged' => 'menari'],
            ['label_id' => null, 'name' => 'melukis', 'name_tagged' => 'melukis'],
            ['label_id' => null, 'name' => 'menggambar', 'name_tagged' => 'menggambar'],
            ['label_id' => null, 'name' => 'berbicara', 'name_tagged' => 'berbicara'],
            ['label_id' => null, 'name' => 'mendengar', 'name_tagged' => 'mendengar'],
            ['label_id' => null, 'name' => 'melihat', 'name_tagged' => 'melihat'],
            ['label_id' => null, 'name' => 'merasakan', 'name_tagged' => 'merasakan'],
            ['label_id' => null, 'name' => 'mencium', 'name_tagged' => 'mencium'],
            ['label_id' => null, 'name' => 'menyentuh', 'name_tagged' => 'menyentuh'],
            ['label_id' => null, 'name' => 'memberi', 'name_tagged' => 'memberi'],
            ['label_id' => null, 'name' => 'menerima', 'name_tagged' => 'menerima'],
            ['label_id' => null, 'name' => 'mengambil', 'name_tagged' => 'mengambil'],
            ['label_id' => null, 'name' => 'meletakkan', 'name_tagged' => 'meletakkan'],
            ['label_id' => null, 'name' => 'membawa', 'name_tagged' => 'membawa'],
            ['label_id' => null, 'name' => 'mengirim', 'name_tagged' => 'mengirim'],
            ['label_id' => null, 'name' => 'datang', 'name_tagged' => 'datang'],
            ['label_id' => null, 'name' => 'pergi', 'name_tagged' => 'pergi'],
            ['label_id' => null, 'name' => 'pulang', 'name_tagged' => 'pulang'],
            ['label_id' => null, 'name' => 'tiba', 'name_tagged' => 'tiba'],
            ['label_id' => null, 'name' => 'berangkat', 'name_tagged' => 'berangkat'],
            ['label_id' => null, 'name' => 'mencari', 'name_tagged' => 'mencari'],
            ['label_id' => null, 'name' => 'menemukan', 'name_tagged' => 'menemukan'],
            ['label_id' => null, 'name' => 'kehilangan', 'name_tagged' => 'kehilangan'],
            ['label_id' => null, 'name' => 'memiliki', 'name_tagged' => 'memiliki'],
            ['label_id' => null, 'name' => 'membangun', 'name_tagged' => 'membangun'],
            ['label_id' => null, 'name' => 'merusak', 'name_tagged' => 'merusak'],
            ['label_id' => null, 'name' => 'memperbaiki', 'name_tagged' => 'memperbaiki'],
            ['label_id' => null, 'name' => 'membuat', 'name_tagged' => 'membuat'],
            ['label_id' => null, 'name' => 'menghancurkan', 'name_tagged' => 'menghancurkan'],
            ['label_id' => null, 'name' => 'memulai', 'name_tagged' => 'memulai'],
            ['label_id' => null, 'name' => 'mengakhiri', 'name_tagged' => 'mengakhiri'],
            ['label_id' => null, 'name' => 'melanjutkan', 'name_tagged' => 'melanjutkan'],
            ['label_id' => null, 'name' => 'berhenti', 'name_tagged' => 'berhenti'],
            ['label_id' => 1, 'name' => 'ngomong', 'name_tagged' => 'ngomong'],
            ['label_id' => 1, 'name' => 'makan-makan', 'name_tagged' => 'makan-makan'],
            ['label_id' => 1, 'name' => 'nongkrong', 'name_tagged' => 'nongkrong'],
            ['label_id' => 4, 'name' => 'memakan hati', 'name_tagged' => 'memakan hati'],
            ['label_id' => 4, 'name' => 'menelan ludah', 'name_tagged' => 'menelan ludah'],
            ['label_id' => 4, 'name' => 'membanting tulang', 'name_tagged' => 'membanting tulang'],
            
            // Kata benda (Nomina) - berbagai kategori
            ['label_id' => null, 'name' => 'rumah', 'name_tagged' => 'rumah'],
            ['label_id' => null, 'name' => 'sekolah', 'name_tagged' => 'sekolah'],
            ['label_id' => null, 'name' => 'kantor', 'name_tagged' => 'kantor'],
            ['label_id' => null, 'name' => 'pasar', 'name_tagged' => 'pasar'],
            ['label_id' => null, 'name' => 'toko', 'name_tagged' => 'toko'],
            ['label_id' => null, 'name' => 'restoran', 'name_tagged' => 'restoran'],
            ['label_id' => null, 'name' => 'hotel', 'name_tagged' => 'hotel'],
            ['label_id' => null, 'name' => 'jalan', 'name_tagged' => 'jalan'],
            ['label_id' => null, 'name' => 'jembatan', 'name_tagged' => 'jembatan'],
            ['label_id' => null, 'name' => 'gedung', 'name_tagged' => 'gedung'],
            ['label_id' => null, 'name' => 'bangunan', 'name_tagged' => 'bangunan'],
            ['label_id' => null, 'name' => 'mobil', 'name_tagged' => 'mobil'],
            ['label_id' => null, 'name' => 'motor', 'name_tagged' => 'motor'],
            ['label_id' => null, 'name' => 'sepeda', 'name_tagged' => 'sepeda'],
            ['label_id' => null, 'name' => 'bus', 'name_tagged' => 'bus'],
            ['label_id' => null, 'name' => 'kereta api', 'name_tagged' => 'kereta api'],
            ['label_id' => null, 'name' => 'pesawat', 'name_tagged' => 'pesawat'],
            ['label_id' => null, 'name' => 'kapal', 'name_tagged' => 'kapal'],
            ['label_id' => null, 'name' => 'perahu', 'name_tagged' => 'perahu'],
            ['label_id' => null, 'name' => 'buku', 'name_tagged' => 'buku'],
            ['label_id' => null, 'name' => 'majalah', 'name_tagged' => 'majalah'],
            ['label_id' => null, 'name' => 'koran', 'name_tagged' => 'koran'],
            ['label_id' => null, 'name' => 'surat', 'name_tagged' => 'surat'],
            ['label_id' => null, 'name' => 'pensil', 'name_tagged' => 'pensil'],
            ['label_id' => null, 'name' => 'pulpen', 'name_tagged' => 'pulpen'],
            ['label_id' => null, 'name' => 'kertas', 'name_tagged' => 'kertas'],
            ['label_id' => null, 'name' => 'meja', 'name_tagged' => 'meja'],
            ['label_id' => null, 'name' => 'kursi', 'name_tagged' => 'kursi'],
            ['label_id' => null, 'name' => 'tempat tidur', 'name_tagged' => 'tempat tidur'],
            ['label_id' => null, 'name' => 'lemari', 'name_tagged' => 'lemari'],
            ['label_id' => null, 'name' => 'pintu', 'name_tagged' => 'pintu'],
            ['label_id' => null, 'name' => 'jendela', 'name_tagged' => 'jendela'],
            ['label_id' => null, 'name' => 'lampu', 'name_tagged' => 'lampu'],
            ['label_id' => null, 'name' => 'televisi', 'name_tagged' => 'televisi'],
            ['label_id' => null, 'name' => 'komputer', 'name_tagged' => 'komputer'],
            ['label_id' => null, 'name' => 'telepon', 'name_tagged' => 'telepon'],
            ['label_id' => null, 'name' => 'handphone', 'name_tagged' => 'handphone'],
            
            // Makanan dan minuman
            ['label_id' => null, 'name' => 'nasi', 'name_tagged' => 'nasi'],
            ['label_id' => null, 'name' => 'roti', 'name_tagged' => 'roti'],
            ['label_id' => null, 'name' => 'mie', 'name_tagged' => 'mie'],
            ['label_id' => null, 'name' => 'sayur', 'name_tagged' => 'sayur'],
            ['label_id' => null, 'name' => 'buah', 'name_tagged' => 'buah'],
            ['label_id' => null, 'name' => 'daging', 'name_tagged' => 'daging'],
            ['label_id' => null, 'name' => 'ikan', 'name_tagged' => 'ikan'],
            ['label_id' => null, 'name' => 'ayam', 'name_tagged' => 'ayam'],
            ['label_id' => null, 'name' => 'telur', 'name_tagged' => 'telur'],
            ['label_id' => null, 'name' => 'susu', 'name_tagged' => 'susu'],
            ['label_id' => null, 'name' => 'kopi', 'name_tagged' => 'kopi'],
            ['label_id' => null, 'name' => 'teh', 'name_tagged' => 'teh'],
            ['label_id' => null, 'name' => 'air', 'name_tagged' => 'air'],
            ['label_id' => null, 'name' => 'jus', 'name_tagged' => 'jus'],
            
            // Kata sifat (Adjektiva)
            ['label_id' => null, 'name' => 'besar', 'name_tagged' => 'besar'],
            ['label_id' => null, 'name' => 'kecil', 'name_tagged' => 'kecil'],
            ['label_id' => null, 'name' => 'panjang', 'name_tagged' => 'panjang'],
            ['label_id' => null, 'name' => 'pendek', 'name_tagged' => 'pendek'],
            ['label_id' => null, 'name' => 'tinggi', 'name_tagged' => 'tinggi'],
            ['label_id' => null, 'name' => 'rendah', 'name_tagged' => 'rendah'],
            ['label_id' => null, 'name' => 'luas', 'name_tagged' => 'luas'],
            ['label_id' => null, 'name' => 'sempit', 'name_tagged' => 'sempit'],
            ['label_id' => null, 'name' => 'tebal', 'name_tagged' => 'tebal'],
            ['label_id' => null, 'name' => 'tipis', 'name_tagged' => 'tipis'],
            ['label_id' => null, 'name' => 'berat', 'name_tagged' => 'berat'],
            ['label_id' => null, 'name' => 'ringan', 'name_tagged' => 'ringan'],
            ['label_id' => null, 'name' => 'cantik', 'name_tagged' => 'cantik'],
            ['label_id' => null, 'name' => 'tampan', 'name_tagged' => 'tampan'],
            ['label_id' => null, 'name' => 'jelek', 'name_tagged' => 'jelek'],
            ['label_id' => null, 'name' => 'indah', 'name_tagged' => 'indah'],
            ['label_id' => null, 'name' => 'buruk', 'name_tagged' => 'buruk'],
            ['label_id' => null, 'name' => 'baik', 'name_tagged' => 'baik'],
            ['label_id' => null, 'name' => 'jahat', 'name_tagged' => 'jahat'],
            ['label_id' => null, 'name' => 'pintar', 'name_tagged' => 'pintar'],
            ['label_id' => null, 'name' => 'bodoh', 'name_tagged' => 'bodoh'],
            ['label_id' => null, 'name' => 'rajin', 'name_tagged' => 'rajin'],
            ['label_id' => null, 'name' => 'malas', 'name_tagged' => 'malas'],
            ['label_id' => null, 'name' => 'cepat', 'name_tagged' => 'cepat'],
            ['label_id' => null, 'name' => 'lambat', 'name_tagged' => 'lambat'],
            ['label_id' => null, 'name' => 'panas', 'name_tagged' => 'panas'],
            ['label_id' => null, 'name' => 'dingin', 'name_tagged' => 'dingin'],
            ['label_id' => null, 'name' => 'hangat', 'name_tagged' => 'hangat'],
            ['label_id' => null, 'name' => 'sejuk', 'name_tagged' => 'sejuk'],
            ['label_id' => null, 'name' => 'panas', 'name_tagged' => 'panas'],
            ['label_id' => null, 'name' => 'terang', 'name_tagged' => 'terang'],
            ['label_id' => null, 'name' => 'gelap', 'name_tagged' => 'gelap'],
            ['label_id' => null, 'name' => 'ramai', 'name_tagged' => 'ramai'],
            ['label_id' => null, 'name' => 'sepi', 'name_tagged' => 'sepi'],
            ['label_id' => null, 'name' => 'keras', 'name_tagged' => 'keras'],
            ['label_id' => null, 'name' => 'lembut', 'name_tagged' => 'lembut'],
            ['label_id' => null, 'name' => 'kasar', 'name_tagged' => 'kasar'],
            ['label_id' => null, 'name' => 'halus', 'name_tagged' => 'halus'],
            ['label_id' => null, 'name' => 'kuat', 'name_tagged' => 'kuat'],
            ['label_id' => null, 'name' => 'lemah', 'name_tagged' => 'lemah'],
            ['label_id' => null, 'name' => 'berani', 'name_tagged' => 'berani'],
            ['label_id' => null, 'name' => 'penakut', 'name_tagged' => 'penakut'],
            ['label_id' => null, 'name' => 'sabar', 'name_tagged' => 'sabar'],
            ['label_id' => null, 'name' => 'marah', 'name_tagged' => 'marah'],
            ['label_id' => null, 'name' => 'senang', 'name_tagged' => 'senang'],
            ['label_id' => null, 'name' => 'sedih', 'name_tagged' => 'sedih'],
            ['label_id' => null, 'name' => 'gembira', 'name_tagged' => 'gembira'],
            ['label_id' => null, 'name' => 'murung', 'name_tagged' => 'murung'],
            
            // Bilangan (Numeralia)
            ['label_id' => null, 'name' => 'satu', 'name_tagged' => 'satu'],
            ['label_id' => null, 'name' => 'dua', 'name_tagged' => 'dua'],
            ['label_id' => null, 'name' => 'tiga', 'name_tagged' => 'tiga'],
            ['label_id' => null, 'name' => 'empat', 'name_tagged' => 'empat'],
            ['label_id' => null, 'name' => 'lima', 'name_tagged' => 'lima'],
            ['label_id' => null, 'name' => 'enam', 'name_tagged' => 'enam'],
            ['label_id' => null, 'name' => 'tujuh', 'name_tagged' => 'tujuh'],
            ['label_id' => null, 'name' => 'delapan', 'name_tagged' => 'delapan'],
            ['label_id' => null, 'name' => 'sembilan', 'name_tagged' => 'sembilan'],
            ['label_id' => null, 'name' => 'sepuluh', 'name_tagged' => 'sepuluh'],
            ['label_id' => null, 'name' => 'sebelas', 'name_tagged' => 'sebelas'],
            ['label_id' => null, 'name' => 'dua belas', 'name_tagged' => 'dua belas'],
            ['label_id' => null, 'name' => 'seratus', 'name_tagged' => 'seratus'],
            ['label_id' => null, 'name' => 'seribu', 'name_tagged' => 'seribu'],
            ['label_id' => null, 'name' => 'sejuta', 'name_tagged' => 'sejuta'],
            ['label_id' => null, 'name' => 'pertama', 'name_tagged' => 'pertama'],
            ['label_id' => null, 'name' => 'kedua', 'name_tagged' => 'kedua'],
            ['label_id' => null, 'name' => 'ketiga', 'name_tagged' => 'ketiga'],
            
            // Orang dan profesi
            ['label_id' => null, 'name' => 'guru', 'name_tagged' => 'guru'],
            ['label_id' => null, 'name' => 'dosen', 'name_tagged' => 'dosen'],
            ['label_id' => null, 'name' => 'dokter', 'name_tagged' => 'dokter'],
            ['label_id' => null, 'name' => 'perawat', 'name_tagged' => 'perawat'],
            ['label_id' => null, 'name' => 'polisi', 'name_tagged' => 'polisi'],
            ['label_id' => null, 'name' => 'tentara', 'name_tagged' => 'tentara'],
            ['label_id' => null, 'name' => 'pengusaha', 'name_tagged' => 'pengusaha'],
            ['label_id' => null, 'name' => 'petani', 'name_tagged' => 'petani'],
            ['label_id' => null, 'name' => 'nelayan', 'name_tagged' => 'nelayan'],
            ['label_id' => null, 'name' => 'pedagang', 'name_tagged' => 'pedagang'],
            ['label_id' => null, 'name' => 'karyawan', 'name_tagged' => 'karyawan'],
            ['label_id' => null, 'name' => 'pegawai', 'name_tagged' => 'pegawai'],
            ['label_id' => null, 'name' => 'direktur', 'name_tagged' => 'direktur'],
            ['label_id' => null, 'name' => 'manajer', 'name_tagged' => 'manajer'],
            ['label_id' => null, 'name' => 'sekretaris', 'name_tagged' => 'sekretaris'],
            ['label_id' => null, 'name' => 'programmer', 'name_tagged' => 'programmer'],
            ['label_id' => null, 'name' => 'desainer', 'name_tagged' => 'desainer'],
            ['label_id' => null, 'name' => 'arsitek', 'name_tagged' => 'arsitek'],
            ['label_id' => null, 'name' => 'insinyur', 'name_tagged' => 'insinyur'],
            ['label_id' => null, 'name' => 'peneliti', 'name_tagged' => 'peneliti'],
            ['label_id' => null, 'name' => 'ilmuwan', 'name_tagged' => 'ilmuwan'],
            ['label_id' => null, 'name' => 'seniman', 'name_tagged' => 'seniman'],
            ['label_id' => null, 'name' => 'musisi', 'name_tagged' => 'musisi'],
            ['label_id' => null, 'name' => 'penyanyi', 'name_tagged' => 'penyanyi'],
            ['label_id' => null, 'name' => 'penari', 'name_tagged' => 'penari'],
            ['label_id' => null, 'name' => 'pelukis', 'name_tagged' => 'pelukis'],
            ['label_id' => null, 'name' => 'penulis', 'name_tagged' => 'penulis'],
            ['label_id' => null, 'name' => 'jurnalis', 'name_tagged' => 'jurnalis'],
            ['label_id' => null, 'name' => 'wartawan', 'name_tagged' => 'wartawan'],
            
            // Keluarga
            ['label_id' => null, 'name' => 'ayah', 'name_tagged' => 'ayah'],
            ['label_id' => null, 'name' => 'ibu', 'name_tagged' => 'ibu'],
            ['label_id' => null, 'name' => 'kakak', 'name_tagged' => 'kakak'],
            ['label_id' => null, 'name' => 'adik', 'name_tagged' => 'adik'],
            ['label_id' => null, 'name' => 'kakek', 'name_tagged' => 'kakek'],
            ['label_id' => null, 'name' => 'nenek', 'name_tagged' => 'nenek'],
            ['label_id' => null, 'name' => 'paman', 'name_tagged' => 'paman'],
            ['label_id' => null, 'name' => 'bibi', 'name_tagged' => 'bibi'],
            ['label_id' => null, 'name' => 'sepupu', 'name_tagged' => 'sepupu'],
            ['label_id' => null, 'name' => 'suami', 'name_tagged' => 'suami'],
            ['label_id' => null, 'name' => 'istri', 'name_tagged' => 'istri'],
            ['label_id' => null, 'name' => 'anak', 'name_tagged' => 'anak'],
            ['label_id' => null, 'name' => 'cucu', 'name_tagged' => 'cucu'],
            
            // Alam dan lingkungan
            ['label_id' => null, 'name' => 'matahari', 'name_tagged' => 'matahari'],
            ['label_id' => null, 'name' => 'bulan', 'name_tagged' => 'bulan'],
            ['label_id' => null, 'name' => 'bintang', 'name_tagged' => 'bintang'],
            ['label_id' => null, 'name' => 'langit', 'name_tagged' => 'langit'],
            ['label_id' => null, 'name' => 'awan', 'name_tagged' => 'awan'],
            ['label_id' => null, 'name' => 'hujan', 'name_tagged' => 'hujan'],
            ['label_id' => null, 'name' => 'angin', 'name_tagged' => 'angin'],
            ['label_id' => null, 'name' => 'petir', 'name_tagged' => 'petir'],
            ['label_id' => null, 'name' => 'guntur', 'name_tagged' => 'guntur'],
            ['label_id' => null, 'name' => 'pelangi', 'name_tagged' => 'pelangi'],
            ['label_id' => null, 'name' => 'gunung', 'name_tagged' => 'gunung'],
            ['label_id' => null, 'name' => 'bukit', 'name_tagged' => 'bukit'],
            ['label_id' => null, 'name' => 'lembah', 'name_tagged' => 'lembah'],
            ['label_id' => null, 'name' => 'sungai', 'name_tagged' => 'sungai'],
            ['label_id' => null, 'name' => 'danau', 'name_tagged' => 'danau'],
            ['label_id' => null, 'name' => 'laut', 'name_tagged' => 'laut'],
            ['label_id' => null, 'name' => 'pantai', 'name_tagged' => 'pantai'],
            ['label_id' => null, 'name' => 'hutan', 'name_tagged' => 'hutan'],
            ['label_id' => null, 'name' => 'pohon', 'name_tagged' => 'pohon'],
            ['label_id' => null, 'name' => 'bunga', 'name_tagged' => 'bunga'],
            ['label_id' => null, 'name' => 'rumput', 'name_tagged' => 'rumput'],
            ['label_id' => null, 'name' => 'tanah', 'name_tagged' => 'tanah'],
            ['label_id' => null, 'name' => 'batu', 'name_tagged' => 'batu'],
            ['label_id' => null, 'name' => 'pasir', 'name_tagged' => 'pasir'],
            
            // Hewan
            ['label_id' => null, 'name' => 'kucing', 'name_tagged' => 'kucing'],
            ['label_id' => null, 'name' => 'anjing', 'name_tagged' => 'anjing'],
            ['label_id' => null, 'name' => 'burung', 'name_tagged' => 'burung'],
            ['label_id' => null, 'name' => 'sapi', 'name_tagged' => 'sapi'],
            ['label_id' => null, 'name' => 'kerbau', 'name_tagged' => 'kerbau'],
            ['label_id' => null, 'name' => 'kambing', 'name_tagged' => 'kambing'],
            ['label_id' => null, 'name' => 'domba', 'name_tagged' => 'domba'],
            ['label_id' => null, 'name' => 'kuda', 'name_tagged' => 'kuda'],
            ['label_id' => null, 'name' => 'harimau', 'name_tagged' => 'harimau'],
            ['label_id' => null, 'name' => 'singa', 'name_tagged' => 'singa'],
            ['label_id' => null, 'name' => 'gajah', 'name_tagged' => 'gajah'],
            ['label_id' => null, 'name' => 'monyet', 'name_tagged' => 'monyet'],
            ['label_id' => null, 'name' => 'ular', 'name_tagged' => 'ular'],
            ['label_id' => null, 'name' => 'katak', 'name_tagged' => 'katak'],
            ['label_id' => null, 'name' => 'kelinci', 'name_tagged' => 'kelinci'],
            ['label_id' => null, 'name' => 'tikus', 'name_tagged' => 'tikus'],
            
            // Waktu
            ['label_id' => null, 'name' => 'hari', 'name_tagged' => 'hari'],
            ['label_id' => null, 'name' => 'minggu', 'name_tagged' => 'minggu'],
            ['label_id' => null, 'name' => 'bulan', 'name_tagged' => 'bulan'],
            ['label_id' => null, 'name' => 'tahun', 'name_tagged' => 'tahun'],
            ['label_id' => null, 'name' => 'pagi', 'name_tagged' => 'pagi'],
            ['label_id' => null, 'name' => 'siang', 'name_tagged' => 'siang'],
            ['label_id' => null, 'name' => 'sore', 'name_tagged' => 'sore'],
            ['label_id' => null, 'name' => 'malam', 'name_tagged' => 'malam'],
            ['label_id' => null, 'name' => 'kemarin', 'name_tagged' => 'kemarin'],
            ['label_id' => null, 'name' => 'hari ini', 'name_tagged' => 'hari ini'],
            ['label_id' => null, 'name' => 'besok', 'name_tagged' => 'besok'],
            ['label_id' => null, 'name' => 'lusa', 'name_tagged' => 'lusa'],
            ['label_id' => null, 'name' => 'dulu', 'name_tagged' => 'dulu'],
            ['label_id' => null, 'name' => 'sekarang', 'name_tagged' => 'sekarang'],
            ['label_id' => null, 'name' => 'nanti', 'name_tagged' => 'nanti'],
            
            // Kata keterangan (Adverbia)
            ['label_id' => null, 'name' => 'sangat', 'name_tagged' => 'sangat'],
            ['label_id' => null, 'name' => 'terlalu', 'name_tagged' => 'terlalu'],
            ['label_id' => null, 'name' => 'agak', 'name_tagged' => 'agak'],
            ['label_id' => null, 'name' => 'sedikit', 'name_tagged' => 'sedikit'],
            ['label_id' => null, 'name' => 'banyak', 'name_tagged' => 'banyak'],
            ['label_id' => null, 'name' => 'selalu', 'name_tagged' => 'selalu'],
            ['label_id' => null, 'name' => 'sering', 'name_tagged' => 'sering'],
            ['label_id' => null, 'name' => 'kadang-kadang', 'name_tagged' => 'kadang-kadang'],
            ['label_id' => null, 'name' => 'jarang', 'name_tagged' => 'jarang'],
            ['label_id' => null, 'name' => 'tidak pernah', 'name_tagged' => 'tidak pernah'],
            ['label_id' => null, 'name' => 'sudah', 'name_tagged' => 'sudah'],
            ['label_id' => null, 'name' => 'belum', 'name_tagged' => 'belum'],
            ['label_id' => null, 'name' => 'sedang', 'name_tagged' => 'sedang'],
            ['label_id' => null, 'name' => 'akan', 'name_tagged' => 'akan'],
            
            // Kata hubung (Konjungsi)
            ['label_id' => null, 'name' => 'dan', 'name_tagged' => 'dan'],
            ['label_id' => null, 'name' => 'atau', 'name_tagged' => 'atau'],
            ['label_id' => null, 'name' => 'tetapi', 'name_tagged' => 'tetapi'],
            ['label_id' => null, 'name' => 'namun', 'name_tagged' => 'namun'],
            ['label_id' => null, 'name' => 'karena', 'name_tagged' => 'karena'],
            ['label_id' => null, 'name' => 'sebab', 'name_tagged' => 'sebab'],
            ['label_id' => null, 'name' => 'jika', 'name_tagged' => 'jika'],
            ['label_id' => null, 'name' => 'kalau', 'name_tagged' => 'kalau'],
            ['label_id' => null, 'name' => 'ketika', 'name_tagged' => 'ketika'],
            ['label_id' => null, 'name' => 'saat', 'name_tagged' => 'saat'],
            ['label_id' => null, 'name' => 'sebelum', 'name_tagged' => 'sebelum'],
            ['label_id' => null, 'name' => 'sesudah', 'name_tagged' => 'sesudah'],
            ['label_id' => null, 'name' => 'setelah', 'name_tagged' => 'setelah'],
            ['label_id' => null, 'name' => 'supaya', 'name_tagged' => 'supaya'],
            ['label_id' => null, 'name' => 'agar', 'name_tagged' => 'agar'],
            ['label_id' => null, 'name' => 'meskipun', 'name_tagged' => 'meskipun'],
            ['label_id' => null, 'name' => 'walaupun', 'name_tagged' => 'walaupun'],
            ['label_id' => null, 'name' => 'sehingga', 'name_tagged' => 'sehingga'],
            
            // Warna
            ['label_id' => null, 'name' => 'merah', 'name_tagged' => 'merah'],
            ['label_id' => null, 'name' => 'kuning', 'name_tagged' => 'kuning'],
            ['label_id' => null, 'name' => 'hijau', 'name_tagged' => 'hijau'],
            ['label_id' => null, 'name' => 'biru', 'name_tagged' => 'biru'],
            ['label_id' => null, 'name' => 'putih', 'name_tagged' => 'putih'],
            ['label_id' => null, 'name' => 'hitam', 'name_tagged' => 'hitam'],
            ['label_id' => null, 'name' => 'coklat', 'name_tagged' => 'coklat'],
            ['label_id' => null, 'name' => 'ungu', 'name_tagged' => 'ungu'],
            ['label_id' => null, 'name' => 'pink', 'name_tagged' => 'pink'],
            ['label_id' => null, 'name' => 'orange', 'name_tagged' => 'orange'],
            ['label_id' => null, 'name' => 'abu-abu', 'name_tagged' => 'abu-abu'],
        ];

        DB::table('lemma')->insert($lemmas);
        
        $this->command->info('Berhasil menambahkan ' . count($lemmas) . ' data lemma.');
    }
}
